README.md, app/router.js, app/routes/add.js, app/routes/application.js, app/routes/scan.js, app/routes/search.js, app/routes/transfer.js, app/styles/app.css, app/templates/add.hbs, app/templates/application.hbs, app/templates/scan.hbs, app/templates/search.hbs, app/templates/transfer.hbs, bower.json, ember-cli-build.js, tests/unit/routes/add-test.js, tests/unit/routes/application-test.js, tests/unit/routes/scan-test.js, tests/unit/routes/search-test.js, tests/unit/routes/transfer-test.js
Initializing core routes
1. ```application```
2. ```add```
3. ```search```
4. ```transfer```
5. ```scan```
Added temp styling to give an idea of what it is looking like. ```INTENDED TO BE FIXED BY UX DESIGNER! IT IS BAD CSS!!!```
=> Josiahc.init app page

app/authenticators/oauth2.js, app/controllers/application.js, app/styles/app.css, app/templates/application.hbs
1. Added dynamic header text
2. fixed 2 issues in ```/authorizers/application.js```
3. add css for login/logout button
4. add css for page view div
=> Add Dynamic header

app/routes/scan.js, app/routes/search.js, app/styles/app.css, app/templates/scan.hbs, app/templates/search.hbs
Added 'Brand' as a search parameter for both search and tool pages
=> Amos.add brand parameter

app/adapters/application.js, app/authenticators/oauth2.js, app/models/owner.js, app/models/tool.js, app/routes/add.js, app/routes/index.js, app/routes/scan.js, app/routes/search.js, app/templates/add.hbs, app/templates/scan.hbs, app/templates/search.hbs, config/environment.js
Very varied and widespread changes made 😬  but some of the key points
1. Login authenticates using the develop API (caches acces_token and userid)
2. Dropdowns populated from API
3. Index route now transitions to the Transfer page per UX team request
4. Modified Tool model to have `username` instead of first name and last name
=> Fixing issues related to connecting to the API

app/adapters/application.js, app/authenticators/oauth2.js, app/controllers/add.js, app/controllers/info.js, app/controllers/scan.js, app/routes/add.js, app/routes/search.js, app/templates/add.hbs, app/templates/scan.hbs, app/templates/search.hbs
Add tool page now successfully adds a tool and transitions the user to the info page with all of the tool info
=> Add Page (needs UX and validation still)

app/adapters/application.js, app/authenticators/oauth2.js, app/controllers/info.js, app/controllers/scan.js, app/controllers/search.js, app/routes/scan.js, app/routes/search.js, app/templates/info.hbs, app/templates/scan.hbs, app/templates/search.hbs, mirage/config.js
Got the filter searches and the fuzzy searches for both the add and transfer pages operational. 
Fixed several of the errors that you see when you run ember server. There are just 2 warnings left about defining but never using a variable. These are because I commented out most of what I was trying to do for the change status feature. Will go away when the feature is implemented.
Fixed the api calls on the transfer page so the dropdown for users only shows yourself and the shop manager, but the transfer to dropdown shows all users.
Made an attempt to fix the status change api call. Made some progress but didn't finish. Commented out what I was working on an have an alert that the feature is in progress. Will fix today if I can.
Feel free to give this one a thorough looking over and let me …
=> Live Search

app/controllers/add.js, app/controllers/scan.js, app/controllers/search.js, app/styles/app.css, app/templates/add.hbs, app/templates/scan.hbs
1. Login button is fixed
2. Made cart section of transfer page bigger, larger fonts
3. Transfer page now alerts user after transfer is complete
4. Increased font size of details in search or transfer page
5. Add page UX updates
6. Fixed add page layout, added "other" option on certain drop downs to open a text field
=> Amos.ux changes 3

app/routes/add.js, app/templates/add.hbs
Ok ya'll. This is the most horrendous code i have ever written, but i think it works :)
=> Eliask.datelabel

ember-cli-build.js
fixes regression documented in #74
=> added jquery validation import to fix validation on release_2.1.0

app/controllers/login.js, app/controllers/search.js, app/styles/app.css, app/templates/login.hbs
fixing issue #72 
Giving the login fail message a better description and making the text white. @amenders may want to change some style aspects of it but other than the css we are good to go.
=> fixing failed login message

app/controllers/scan.js, app/routes/scan.js, app/templates/scan.hbs, app/templates/search.hbs, package.json
1. Addressing issue #66 
2. Also we were having all blank users in our search results because of a small error in the hbs. Fixed that as well
this is not a long term solution to the problem but a good long term solution would require a refactor so I thought it would be better to target a major refactor for Release 3.0.0
=> Addressing issue #66

app/styles/app.css, app/templates/add.hbs
Sorry I got a little merge happy and merged in a css change that prevented the add page from scrolling. This restores scrolling to the add page
=> Josiahc.unfreeze addpage scroll

app/routes/scan.js
Wow I really put my foot in my mouth : ) Delete a method and yay! we have persistance 😝
=> Make the Transfer Cart Persist

app/controllers/scan.js
Accidentally left the old jquery clear. Was messing up ember.
=> fix for issue #93

app/controllers/login.js
=> implemented loading state on login

app/templates/scan.hbs
=> added status to tool listings on transfer page

app/routes/scan.js
This was a bug introduced by #108
=> fixing issue introduced by my persist search PR

app/styles/app.css, app/templates/info.hbs
Please test the 'callability' feature of the phone numbers on the info page on a PHONE NUMBER THAT IS KNOWN.
fix for #115 #116 #117
=> Amose.info page updates

app/controllers/add.js, app/routes/add.js, app/templates/add.hbs, bower.json, package.json
adding better money input to price field on add page that Dad requested
=> [no-ticket] Add Money Input to price field

app/routes/add.js, app/templates/add.hbs
=> [#121] Enforcing DB Rules

app/templates/add.hbs, ember-cli-build.js, package.json
This PR should be fully functional (I went ahead and deployed it to https://retina-app-release.azurewebsites.net). But I need to do some cleanup stuff behind the scenes. I hijacked I library we were using so I could customize it : )
=> [no-ticket] allow empty field to reset {READY FOR REVIEW}

app/controllers/scan.js
=> [#134] Able to transfer a tool with no transferee

app/styles/app.scss, app/styles/variables.scss, package.json
I was able to install sass without having to make any css code changes. We can migrate over to sass style gradually. 
The only change I made in this PR was to create a couple initial variables to make sure sass was working properly and also just to get stuff started.
=> Adding ember-cli-sass to our project

.eslintrc.js, .jscsrc, .jshintrc, app/adapters/tool.js, app/authenticators/oauth2.js, app/controllers/scan.js, app/controllers/search.js, app/routes/scan.js, app/routes/search.js, config/environment.js, mirage/config.js, mirage/factories/dropdowns.js, mirage/factories/tool.js, mirage/factories/users.js, mirage/models/dropdowns.js, mirage/models/tool.js, mirage/models/users.js, mirage/scenarios/default.js, package.json, tests/.eslintrc.js, tests/.jshintrc, tests/acceptance/login-test.js, tests/helpers/destroy-app.js
1) Setting up our fake api for acceptance testing
2) Fixed a couple small issues that seem like they should have broken the app (see comments)
=> Setup for acceptance tests

config/environment.js
I added a new environment that points to my api running locally when you pass `ember s` the `--environment` flag with parameter `development-local-api`
=> adding local api env

.gitignore, .vscode/settings.json, src/components/fab.vue, src/routes/application.vue, src/routes/login.vue, src/styles/drawer.scss, src/styles/variables.scss, yarn.lock
Nearly resolves #194, minus the change password functionality.
=> Amose.#194 finish menu pullout

src/components/extended-fab.vue, src/components/fab.vue, src/components/tool-search-input.vue, src/routes/tools.vue, src/styles/navbar.scss
=> Amose.#195 nav bar styling

.eslintrc.js, src/components/tool-search-input.vue, src/components/tool-search-result.vue, src/components/user-search-input.vue, src/components/user-search-result.vue, src/routes/tool-detail.vue, src/routes/users.vue, src/styles/search-input.scss, src/styles/search-result.scss
=> Amose.#188 users page

src/components/fab.vue, src/routes/tool-detail.vue, src/routes/user-detail.vue, src/routes/users.vue
=> Amose.#189 user detail page

src/components/header-card.vue, src/router.js, src/routes/new-tool.vue, src/routes/new-user.vue, src/routes/tool-detail.vue, src/routes/user-detail.vue, src/routes/users.vue
=> Amose.#209 add users

src/routes/application.vue, src/routes/tool-detail.vue, src/styles/form-inputs.scss
=> Amose.#217 edit tool info

src/components/button-dropdown.vue, src/routes/application.vue, src/routes/tool-detail.vue
resolves #245 and resolves #237
=> Amose.#234 clarify status button

src/components/input-with-icon.vue, src/components/select.vue, src/routes/login.vue, src/routes/new-tool.vue, src/store.js, src/styles/form-inputs.scss, src/styles/variables.scss
=> [RETINA-235] Add Tool Fixes

package.json, src/App.vue, src/components/nfc-encode.vue, src/components/nfc-scan.vue, src/main.js, src/router.js, src/routes/login.vue, src/routes/new-user.vue, src/routes/password-reset.vue, src/routes/tools.vue, src/styles/app.scss, src/styles/toast.scss, yarn.lock
=> [RETINA-197] Password Reset

src/main.js
Closes #201 
A happy consequence of our choice of toast library 😄
=> [RETINA-201] Styled Session Expiration

src/components/add-result.vue, src/components/config-item.vue, src/components/header-card.vue, src/routes/application.vue, src/routes/configuration.vue, src/routes/new-tool.vue, src/routes/tools.vue, src/routes/users.vue, src/styles/drawer.scss
=> Retina 192 config page

src/routes/tool-detail.vue
=> Add OOS Workflow

src/routes/new-tool.vue
=> fixing config item bug

package.json, src/components/tool-search-input.vue, src/routes/tools.vue, yarn.lock
=> [RETINA-309] Fixing transfer for reguler user

src/routes/application.vue, src/styles/drawer.scss
=> [RETINA-350] Add app version to sidebar

src/components/add-photo.vue, src/routes/new-tool.vue, src/routes/tool-detail.vue
=> [RETINA-356] Fix styles for add photo and tool preview

src/apollo.js, src/routes/new-tool.vue, src/utils/api-response-errors.js
=> [RETINA-358] Don't clear all fields when adding another tool

config.xml, src/main.js, src/routes/tools.vue, src/store/modules/auth.js
This was a benign error but caught thanks to rollbar. If pagination is in the middle of loading and you select a tool you can sometimes get console errors to appear
=> [RETINA-363] fix pagination loading

src/mixins/nfc.js, src/routes/user-detail.vue, src/store/modules/users.js
Resolves #368 
Looks like it had been a couple of simple logic issues.
=> Retina 368 user delete issue

config.xml, package.json, src/components/add-button.vue, src/components/basic/dropdown.vue, src/routes/new-tool.vue, src/styles/action-sidebar.scss, src/styles/add-button.scss, src/styles/app.scss, yarn.lock
1. Fix gap at the bottom of the app
2. Fix existing issues with dropdown component
=> styles fixes

src/mixins/nfc.js
https://rollbar.com/Renascentinc/Retina/items/97/
=> [ROLLBAR-97] change contains to includes

src/routes/history.vue
https://rollbar.com/Renascentinc/Retina/items/91/
=> [ROLLBAR-91] fix calling map on undefined error
